# Generated by Django 3.1.2 on 2020-11-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_auto_20201120_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user-icon.jpg', null=True, upload_to=''),
        ),
    ]
